GAME:
  board_size: [5, 5]
MCTS:
  n_simulations: 25
  cpuct: 1.0
  dirichlet_alpha: 1.10
NN:
  n_res_layers: 5
  learning_rate: 0.01
  weight_decay: 0.015
AZ:
  iterations: 1000
  n_games: 5
  queue_len: 200000
  temp:
    treshold: 15
    before: 1
    after: 1
