GAME:
  board_size: [7, 7]
MCTS:
  n_simulations: 25
  cpuct: 2
  dirichlet_alpha: 1.10
NN:
  n_res_layers: 5
  learning_rate: 0.01
  weight_decay: 0.015
AZ:
  iterations: 500
  n_games: 50
  queue_len: 150
  temp:
    treshold: 15
    before: 1
    after: 0.2
